### ISSUE TITLE
Sass Refactoring Issue

### ISSUE THREAD

**Issue by colinsanford** [git-ftp/git-ftp#169]
*Setup*
Lots of sass imports which compile to 1 main stylesheet which is excluded from the repo.

*Scenario:*
A feature is removed, so one of the sass files is also removed.

*Desired Result*
Compiled stylesheet is uploaded.

*Current Result*
In addition to the intentionally removed file being deleted from the live site, the compiled stylesheet (the main site stylesheet) is also deleted upon `git ftp push`. Obviously this is not a good thing.

*Possible Way of Dealing With This*
Before deleting files that aren't tracked in git, maybe the application should check if there are any other references in the `git-ftp-include` that aren't also deleted. If there are other references that aren't deleted it would update it instead of delete it. 

Great app btw, this will be very useful.

**Comment by mkllnk** [comment]
Yepp, I wondered about that reading the code. I refactored that part recently without changing the logic. The algorithm counted the number of deleted files and the number of modified files. If there was at least one modified file, it would upload the target file. If there were only deleted files, it would delete the target file. But that ignores the unchanged files contributing to the target file. I have two ideas for a new algorithm:

1. Delete the target file if **all** source files (modified or not) were deleted. Otherwise upload.
2. Delete the target file if the local file does not exist. Otherwise upload.

I tend to the second one, because it is more agnostic of the relationship between source files (in fact only trigger files) and the target file. It just mirrors the local state which is probably what you want on the server.

What do you think?

**Comment by colinsanford** [comment]
The second one makes sense, assuming it does that check after something happens with one of the source files. That sounds easier to implement too.

**Comment by mkllnk** [comment]
Ok, I pushed a branch with the second solution #170. Would be cool if you could test it.

**Comment by colinsanford** [comment]
Unfortunately includes don't work at all in the `include-delete` branch. When I switch back to the currently released version includes work again. I'm on Mac osx 10.8.5 in case that makes any difference.

**Comment by mkllnk** [comment]
Ok, cool, thanks for testing. We really need to setup Travis to test with Mac OS.

I uploaded another version which might fix your problem, but I can't test with a Mac at the moment.

**Comment by mkllnk** [comment]
@colinsanford Do you have bash installed? If not, what is your default shell?

The output of these two commands would be interesting:
```
/usr/bin/env bash
echo $SHELL
```

**Comment by colinsanford** [comment]
Still not working. Here's the terminal out put you asked for.

```
/usr/bin/env bash
bash-3.2$ echo $SHELL
/bin/bash
```

**Comment by mkllnk** [comment]
Okay, reading `man 1 expr` for OSX revealed that it doesn't support `expr substr`. I used `grep` now and hope that it works. :-)

**Comment by colinsanford** [comment]
Somethings still not quite right unfortunately. I made sure I pulled the latest commits from include-delete, and that it's re-installed from that branch.

**Comment by mkllnk** [comment]
@colinsanford Thanks a lot for your patience. It becomes really difficult now since I don't have OSX to test and I'm just guessing what could go wrong. Can you give an example of what goes wrong? Or can you run the test suite `tests/git-ftp-test.sh`? You have to set some environment variables for that. The test needs to know an FTP server to test with.

**Comment by mkllnk** [comment]
I think we fixed that issue now. Thanks.
