### ISSUE TITLE
Is there a way to push ignored files?

### ISSUE THREAD

**Issue by CLL80** [git-ftp/git-ftp#245]
I have some generated files that I have ignored in git but would still like to push to the server when changed. Is there a way to "unignore" git's ignored files—basically track only in git-ftp while allowing them to remain ignored in git?

**Comment by mkllnk** [comment]
Yes. Here is the latest documentation from the [man page](https://github.com/git-ftp/git-ftp/blob/develop/man/git-ftp.1.md#syncing-untracked-files):

# SYNCING UNTRACKED FILES

The `.git-ftp-include` file specifies intentionally untracked files that Git-ftp should upload.
If you have a file that should always be uploaded, add a line beginning with ! followed by the file's name.
For example, if you have a file called VERSION.txt then add the following line:

        !VERSION.txt

If you have a file that should be uploaded whenever a tracked file changes, add a line beginning with the untracked file's name followed by a colon and the tracked file's name.
For example, if you have a CSS file compiled from an SCSS file then add the following line:

        css/style.css:scss/style.scss

If you have multiple source files, you can add multiple lines for each of them.
Whenever one of the tracked files changes, the upload of the paired untracked file will be triggered.

        css/style.css:scss/style.scss
        css/style.css:scss/mixins.scss

If a local untracked file is deleted, a paired tracked file will trigger the deletion of the remote file on the server.

It is also possible to upload whole directories.
For example, if you use a package manager like composer, you can upload all vendor packages when the file composer.lock changes:

        vendor/:composer.lock

But keep in mind that this will upload all files in the vendor folder, even those that are on the server already.
And it will not delete files from that directory if local files are deleted.

**Comment by CLL80** [comment]
Thanks, but I was unable to get these file to upload using this:

```
!html/css/main.css
!html/css/main.css.map

!html/js/main.min.js
!html/js/main.min.js.map

!html/js/scripts.min.js
!html/js/scripts.min.js.map
```
Or this:

```
html/css/main.css:main.sass
html/css/main.css.map:main.sass

html/js/main.min.js:main.js
html/js/main.min.js.map:main.js

html/js/scripts.min.js:scripts.js
html/js/scripts.min.js.map:scripts.js

```

After adding these to the .git-ftp-include file, I even made changes in the source files (outputting changed generated files) to see if that would cause it to upload, but there is no difference.

Every time I run `git-ftp push -s dev -D`, it shows `There are no files to sync.`

I'm using git-ftp 1.1.0

**Comment by CLL80** [comment]
Hello,

I've followed your instructions, but I still am not able to get these files to be uploaded wtih git-ftp after ignoring them with git. They are still in my project directory after running git rm --cached.

**Comment by CLL80** [comment]
This worked for the first push:
```
html/css/main.css:main.sass
html/css/main.css.map:main.sass
html/js/script.min.js:script.js
html/js/script.min.js.map:script.js
html/js/main.min.js:script.js
html/js/main.min.js.map:script.js
```
 but any change to these files after that is returning `There are no files to sync.`

**Comment by mkllnk** [comment]
It looks like you are doing everything right. Okay, I had another look into the code and I think I found the problem. The file `.git-ftp-include` is only considered if there are any other files to upload. That's a bug. Thank you for the detailed report.

**Comment by mkllnk** [comment]
The normal use case is that you still track your source files with git, but that you don't upload them by putting them into `.git-ftp-ignore`.

**Comment by mkllnk** [comment]
If you want to use source/target pairs in `.git-ftp-include`, you have to track the source file in git. Because the target file is only uploaded if the source file changes between commits.

If you use only a target proceeded by `!`, the target is always uploaded. No matter if it changed or not. This didn't work if no other files changed at all. But I fixed that in the current develop branch. It should work if you download that version.

```
# main.css is only uploaded if main.sass is tracked by Git and changes between commits
html/css/main.css:main.sass

# main.css is always uploaded, even if it didn't change
!html/css/main.css
```

**Comment by CLL80** [comment]
Thanks, mk. Yes, I'm still tracking the source files. The corresponding generated files are still not being uploaded when git-ftp pushing:

in `.gitignore`
```
/html/css/main.css
/html/css/main.css.map
/html/js/main.min.js
/html/js/main.min.js.map
/html/js/scripts.min.js
/html/js/scripts.min.js.map
```

In .git-ftp-include:
```
html/css/main.css:main.sass
html/css/main.css.map:main.sass
html/js/main.min.js:main.js
html/js/main.min.js.map:main.js
html/js/scripts.min.js:scripts.js
html/js/scripts.min.js.map:scripts.js
```

main.sass, scripts.js and main.js are all tracked in git. I changed all three of those, committed, pushed, and I still get:

```
There are no files to sync.
Last deployment changed to 9d23706009f0d4d82ed4641f96f6bd98c16bba49.
```

using git-ftp version 1.2.0-UNRELEASED

However, using `!` does seem to always upload now. Thanks for that. I'd love to be able to use the source file change/generated file upload feature at some point.

**Comment by mkllnk** [comment]
This is strange. It should at least upload your changed source files. Or do you have a `.git-ftp-ignore` file as well?

**Comment by CLL80** [comment]
I do have a `.git-ftp-ignore` file, but the source files are actually not in the the directory I'm tracking with git-ftp. I'm pretty sure they would be uploaded if they were, as any other file is uploaded when changed directly. I track the main directory (containing the source files) with git and set a dist/html directory that is inside this to be tracked with git-ftp. Here's an example of my structure.

```
project -> html         -> index.php
(git)     (git-ftp)
           main.sass    -> css        -> main.css
                                      -> main.map.css
           main.js      -> js         -> main.min.js
                                      -> main.min.map.js
           scripts.js                 -> scripts.min.js
                                      -> scripts.min.map.js
```

It seems like the project directory not being tracked by git-ftp might be the issue, right? If so, I think it would be very helpful to accommodate for a situation like this, if possible. I know it's very common for projects to not upload source files.

**Comment by mkllnk** [comment]
Now it makes sense. Git-ftp is not tracking the source files. It doesn't know that the source files changed and doesn't upload the target files because of that.

I'm not sure how to solve that. Here is how it works at the moment:

- List all changes files to upload and store them in a file `$changed_files`.
- Read `.git-ftp-include` and for each target-source pair:
 - Check if the source is in `$changed_files`.

Maybe we could change this last check. Instead of using `grep` to lookup the file name in the list of changed files, we could ask git:
```sh
if git diff --quiet "$DEPLOYED_SHA1" -- "$SYNCROOT/$SOURCE"; then
  # nothing changed
else
  # include target into files to upload
fi
```

That should do the same as before. To solve your problem, we would need to add a new syntax to specify paths from git root instead of the git-ftp syncroot. We could use a slash `/` at the beginning. Git uses that for paths in `.git-ignore` as well. You would have this in your `.git-ftp-include`:
```
# Assuming that your syncroot is `dist`
html/css/main.css:/main.sass
```

The method above would then look for the slash at the beginning. If there is a slash, it passes that path straigt to git-diff. Otherwise, it puts the `$SYNCROOT` it front as usual.

Can you follow me? Do you think that sounds good?

Since this is another API change, I'm wondering if I should move that to another release (1.3).

**Comment by CLL80** [comment]
I think this sounds great, and the syntax makes sense. This would also allow git-ftp to be used to upload just the changed dist files created with bundlers like webpack. Thanks for your attention to this 'issue'...or now I think I should say 'feature request'.

I agree re: the version increment.

**Comment by mkllnk** [comment]
I pushed that feature to the *include* branch. You can try it out if you like.

**Comment by CLL80** [comment]
Thanks for working on this.

I think I have the right branch, but I didn't see any include branch. I cloned and checked out the current develop branch (1.3.0-unreleased). Took a look at the diff. It seems correct. I installed and checked the version. However, it always uploads all the files in my git-ftp-include file. No matter if they are changed or not.
```
Mac-Pro:site user$ git status
# On branch master
# Your branch is ahead of 'origin/master' by 1 commit.
#   (use "git push" to publish your local commits)
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   current.sass
#
no changes added to commit (use "git add" and/or "git commit -a")
Mac-Pro:site user$ git commit -am "Testing git-ftp ignore-include functionality"
[master 8b5a338] Testing git-ftp ignore-include functionality
 1 file changed, 1 insertion(+), 1 deletion(-)
Mac-Pro:site user$ git push
Counting objects: 7, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 544 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
To git@gitlab.com:USER/site.git
   e03881e..8b5a338  master -> master
Mac-Pro:site user$ git-ftp push -s master
/print.sass
/current.sass
/home.js
/site.js
/log-in.js
/resume.js
/contact.js
/agreement.js
8 files to sync:
[1 of 8] Buffered for upload 'html/content/css/current.css'.
[2 of 8] Buffered for upload 'html/content/css/print.css'.
[3 of 8] Buffered for upload 'html/content/js/agreement.min.js'.
[4 of 8] Buffered for upload 'html/content/js/contact.min.js'.
[5 of 8] Buffered for upload 'html/content/js/home.min.js'.
[6 of 8] Buffered for upload 'html/content/js/log-in.min.js'.
[7 of 8] Buffered for upload 'html/content/js/resume.min.js'.
[8 of 8] Buffered for upload 'html/content/js/site.min.js'.
Uploading ...
Last deployment changed to 8b5a33822c0bd09db495d03a3c9b53f6f1f3115a.
```

I tried a few times, thinking that maybe this would happen only on the first run, but it actually happened every time I git-ftp pushed.

Here is my `.gitignore`:
```
html/content/css/print.css
html/content/css/print.css.map
html/content/css/current.css
html/content/css/current.css.map
html/content/js/home.min.js
html/content/js/home.min.js.map
html/content/js/site.min.js
html/content/js/site.min.js.map
html/content/js/log-in.min.js
html/content/js/log-in.min.js.map
html/content/js/resume.min.js
html/content/js/resume.min.js.map
html/content/js/contact.min.js
html/content/js/contact.min.js.map
html/content/js/agreement.min.js
html/content/js/agreement.min.js.map
```

Here is my `.git-ftp-include`:
```
html/content/css/print.css:/print.sass
html/content/css/current.css:/current.sass
html/content/js/home.min.js:/home.js
html/content/js/site.min.js:/site.js
html/content/js/log-in.min.js:/log-in.js
html/content/js/resume.min.js:/resume.js
html/content/js/contact.min.js:/contact.js
html/content/js/agreement.min.js:/agreement.js
```

My structure is like this:
```
project-directory/-- print.sass
                  -- current.sass
                  -- html/         -- content/ -- css/ -- print.css
                                   -- content/ -- css/ -- current.css
```

**Comment by mkllnk** [comment]
Thanks a lot for that report. And sorry for the missing branch, I deleted it after I merged the changes into the develop branch. I added some more tests and found a mistake in the removal of the leading `/`. I think I fixed it now.

**Comment by CLL80** [comment]
It's the least I could do. Thanks for working on this enhancement. I just ran git-ftp and it seems to work as you described—only the file I changed was pushed. Looks good to me so far.

**Comment by mkllnk** [comment]
Okay, feel free to open new issues if you run into them.
